name: Build-F2

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  compile:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5 

      - name: Setup
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: msbuild ./PhysicsGame.sln /p:Configuration=Debug /p:Platform=win32

      - name: Create artifact Directory
        run:  mkdir artifact
              mkdir artifact/PhysicsGame
        
