name: Build-F2

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  compile:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5 

      - name: Setup
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: msbuild ./PhysicsGame.sln /p:Configuration=Debug /p:Platform=win32

      - name: Create artifact Directory
        run:  mkdir artifact

      - name: Copy Artifacts
        run: copy ./Build/PhysicsGame/Release/Win32/PhysicsGame.exe ./artifact

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./artifact
          name: Physics-artifact
        
              
        
