name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild PhysicsGame.sln /p:Configuration=Release

      - name: Create artifact directory
        run:  |
          mkdir ./artifact
          mkdir ./artifact/PhysicsGame

      - name: Copy the executable to the artifact directory
        run:  copy ./Build/PhysicsGame/Release/win32/PhysicsGame.exe ./artifact/PhysicsGame/

      - name: Upload artifact
        uses: actions/upload-artifact@v4 
        with: 
          name: my-artifact
          path: ./artifact/
          
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: ./artifact

      - name: Create Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        with:
          title: New release

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: ./artifact

      - name: Github release
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: zip
          GHR_PATH: ./artifact/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
